inherit_gem:
  rubocop-klaustopher: rubocop.yml

AllCops:
  Exclude:
    - bin/*
    - db/migrate/*.rb
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - vendor/bundle/**/*
