name: bump-version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    env:
      BUNDLE_DEPLOYMENT: 0

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Bundle
      run: bundle install

    - name: Bump version
      run: bundle exec rake bump_minor_version

    - name: Update Gemfile.lock
      run: bundle update

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump version
        file_pattern: 'lib/rubocop/klaustopher/version.rb Gemfile.lock'
