name: Check for new Cops

on:
  pull_request_target:
    paths:
      - 'Gemfile.lock'
      - 'rubocop-klaustopher.gemspec'

jobs:
  new-cops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Get warning messages
      run: |
        echo 'RUBOCOP_WARNINGS<<EOF' >> $GITHUB_ENV
        echo "$(bundle exec rubocop --list-target-files 2>&1 1>/dev/null)" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - uses: mshick/add-pr-comment@v2
      if: ${{ contains(env.RUBOCOP_WARNINGS, 'The following cops were added to RuboCop, but are not configured') }}
      with:
        message: |
          We have some new Cops. Please make a decision if they need to be added.

          ```
          ${{ env.RUBOCOP_WARNINGS }}
          ```

    - name: Fail if there are warnings about new cops
      if: ${{ contains(env.RUBOCOP_WARNINGS, 'The following cops were added to RuboCop, but are not configured') }}
      run: |
        echo "::error title=\"New Cops have been added and need to be configured::${{ env.RUBOCOP_WARNINGS }}"
        exit 1

