name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Ruby for sample app
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./sample

      - name: Run rubocop on the gem itself
        run: bundle exec rubocop

      - name: Run Rubocop on sample application
        working-directory: ./sample
        run: bundle exec rubocop --ignore-parent-exclusion
